"""Authentication service: register, login, refresh rotation, logout.

The service is i18n-agnostic — it raises `AppError` subclasses with a
message_key, and the global exception handler in `app.main` translates
them. This keeps the business layer free of HTTP concerns.

Refresh rotation flow:
  1. Client sends refresh_token (plaintext, generated by us).
  2. We hash it and look up the row.
  3. If the row is missing or expired → reject.
  4. If the row is already revoked → REUSE DETECTED. Revoke every active
     token for that user (assume compromise) and reject.
  5. Issue a new access + refresh pair, revoke the old row, link via
     `replaced_by_id` for the audit chain.
"""

from __future__ import annotations

from datetime import UTC, datetime
from uuid import UUID

import structlog

from app.core.exceptions import (
    ConflictError,
    UnauthorizedError,
)
from app.core.security import (
    create_access_token,
    generate_refresh_token,
    hash_password,
    hash_refresh_token,
    refresh_token_expiry,
    verify_password,
)
from app.models.enums import LanguageCode, UserRole
from app.models.user import User
from app.repositories.refresh_token_repository import RefreshTokenRepository
from app.repositories.user_repository import UserRepository

log = structlog.get_logger(__name__)


class AuthService:
    def __init__(
        self,
        *,
        user_repo: UserRepository,
        refresh_token_repo: RefreshTokenRepository,
    ) -> None:
        self.users = user_repo
        self.refresh_tokens = refresh_token_repo

    # ── Registration ─────────────────────────────────────

    async def register(
        self,
        *,
        full_name: str,
        email: str,
        password: str,
        language: LanguageCode = LanguageCode.UZ,
    ) -> User:
        email = email.lower()
        if await self.users.email_exists(email):
            raise ConflictError("auth.emailExists")

        user = User(
            full_name=full_name.strip(),
            email=email,
            password_hash=hash_password(password),
            role=UserRole.USER,  # ← hard-coded; never trust client-supplied role
            language=language,
        )
        return await self.users.add(user)

    # ── Login ────────────────────────────────────────────

    async def login(
        self,
        *,
        email: str,
        password: str,
        user_agent: str | None = None,
        ip_address: str | None = None,
    ) -> tuple[User, str, str]:
        user = await self.users.get_by_email(email)
        if user is None or not verify_password(password, user.password_hash):
            log.warning(
                "auth.login.failed",
                email=email.lower(),
                ip=ip_address,
                user_agent=user_agent,
            )
            raise UnauthorizedError("auth.invalidCredentials")

        log.info("auth.login.success", user_id=str(user.id), ip=ip_address)

        access_token, _ = create_access_token(user.id, role=user.role.value)
        refresh_plain = await self._issue_refresh_token(
            user_id=user.id,
            user_agent=user_agent,
            ip_address=ip_address,
        )
        return user, access_token, refresh_plain

    # ── Refresh (rotation + reuse detection) ─────────────

    async def refresh(
        self,
        *,
        refresh_token: str,
        user_agent: str | None = None,
        ip_address: str | None = None,
    ) -> tuple[User, str, str]:
        token_hash = hash_refresh_token(refresh_token)
        existing = await self.refresh_tokens.get_by_hash(token_hash)

        if existing is None:
            raise UnauthorizedError("auth.refreshInvalid")

        if existing.revoked_at is not None:
            # Reuse of an already-rotated token: assume compromise.
            log.warning(
                "auth.refresh.reuse_detected",
                user_id=str(existing.user_id),
                token_id=str(existing.id),
                ip=ip_address,
            )
            await self.refresh_tokens.revoke_all_for_user(existing.user_id)
            raise UnauthorizedError("auth.refreshInvalid")

        if existing.expires_at < datetime.now(UTC):
            raise UnauthorizedError("auth.refreshInvalid")

        user = await self.users.get(existing.user_id)
        if user is None:
            raise UnauthorizedError("auth.unauthorized")

        new_plain = generate_refresh_token()
        new_row = await self.refresh_tokens.create(
            user_id=user.id,
            token_hash=hash_refresh_token(new_plain),
            expires_at=refresh_token_expiry(),
            user_agent=user_agent,
            ip_address=ip_address,
        )
        await self.refresh_tokens.revoke(existing, replaced_by_id=new_row.id)

        log.info(
            "auth.refresh.rotated",
            user_id=str(user.id),
            old_token_id=str(existing.id),
            new_token_id=str(new_row.id),
        )

        access_token, _ = create_access_token(user.id, role=user.role.value)
        return user, access_token, new_plain

    # ── Logout ───────────────────────────────────────────

    async def logout(self, *, refresh_token: str) -> None:
        token_hash = hash_refresh_token(refresh_token)
        existing = await self.refresh_tokens.get_by_hash(token_hash)
        if existing is not None and existing.revoked_at is None:
            await self.refresh_tokens.revoke(existing)

    async def logout_all(self, *, user_id: UUID) -> int:
        return await self.refresh_tokens.revoke_all_for_user(user_id)

    # ── Helpers ──────────────────────────────────────────

    async def _issue_refresh_token(
        self,
        *,
        user_id: UUID,
        user_agent: str | None,
        ip_address: str | None,
    ) -> str:
        plain = generate_refresh_token()
        await self.refresh_tokens.create(
            user_id=user_id,
            token_hash=hash_refresh_token(plain),
            expires_at=refresh_token_expiry(),
            user_agent=user_agent,
            ip_address=ip_address,
        )
        return plain
