"""Initial schema: users, jobs, applications, messages, saved_jobs, refresh_tokens.

Revision ID: 001_initial_schema
Revises:
Create Date: 2026-05-25

Hand-written rather than autogenerated so we keep full control over:
- pgcrypto + pg_trgm extensions
- Native ENUM types
- Generated tsvector column for full-text search
- Partial / functional indexes (LEAST/GREATEST for conversation lookup,
  WHERE is_read = false for unread fanout, WHERE revoked_at IS NULL for
  active refresh tokens)
- CHECK constraints (no self-message, lowercase email, non-negative salary)
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "001_initial_schema"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# ── ENUM type definitions ─────────────────────────────────
USER_ROLE = postgresql.ENUM("user", "employer", "admin", name="user_role", create_type=False)
LANG_CODE = postgresql.ENUM("uz", "ru", "en", name="lang_code", create_type=False)
JOB_CATEGORY = postgresql.ENUM(
    "IT",
    "Marketing",
    "Design",
    "Finance",
    "Education",
    "Healthcare",
    "Engineering",
    "Sales",
    "Other",
    name="job_category",
    create_type=False,
)
EXPERIENCE_LEVEL = postgresql.ENUM(
    "no-experience", "junior", "mid", "senior", name="experience_level", create_type=False
)
JOB_TYPE = postgresql.ENUM(
    "full-time", "part-time", "remote", "contract", "internship",
    name="job_type",
    create_type=False,
)
APPLICATION_STATUS = postgresql.ENUM(
    "pending", "reviewed", "accepted", "rejected",
    name="application_status",
    create_type=False,
)


def upgrade() -> None:
    bind = op.get_bind()

    # ── Extensions ────────────────────────────────────────
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")

    # ── ENUM types ────────────────────────────────────────
    USER_ROLE.create(bind, checkfirst=True)
    LANG_CODE.create(bind, checkfirst=True)
    JOB_CATEGORY.create(bind, checkfirst=True)
    EXPERIENCE_LEVEL.create(bind, checkfirst=True)
    JOB_TYPE.create(bind, checkfirst=True)
    APPLICATION_STATUS.create(bind, checkfirst=True)

    # ── users ─────────────────────────────────────────────
    op.create_table(
        "users",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("full_name", sa.String(120), nullable=False),
        sa.Column("email", sa.String(255), nullable=False),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("role", USER_ROLE, nullable=False, server_default="user"),
        sa.Column("language", LANG_CODE, nullable=False, server_default="uz"),
        sa.Column("avatar", sa.String(500), nullable=True),
        sa.Column("phone", sa.String(30), nullable=True),
        sa.Column("telegram", sa.String(50), nullable=True),
        sa.Column("bio", sa.String(500), nullable=True),
        sa.Column("title", sa.String(120), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.UniqueConstraint("email", name="uq_users_email"),
        sa.CheckConstraint("email = lower(email)", name="ck_users_email_lowercase"),
    )
    op.create_index("idx_users_role", "users", ["role"])

    # ── jobs ──────────────────────────────────────────────
    op.create_table(
        "jobs",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("company", sa.String(150), nullable=False),
        sa.Column("location", sa.String(150), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("salary_min", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("salary_max", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("salary_currency", sa.String(3), nullable=False, server_default="USD"),
        sa.Column(
            "requirements",
            postgresql.ARRAY(sa.String()),
            nullable=False,
            server_default=sa.text("'{}'::text[]"),
        ),
        sa.Column(
            "skills",
            postgresql.ARRAY(sa.String()),
            nullable=False,
            server_default=sa.text("'{}'::text[]"),
        ),
        sa.Column("category", JOB_CATEGORY, nullable=False),
        sa.Column("experience", EXPERIENCE_LEVEL, nullable=False, server_default="junior"),
        sa.Column("job_type", JOB_TYPE, nullable=False, server_default="full-time"),
        sa.Column("contact_phone", sa.String(30), nullable=True),
        sa.Column("contact_telegram", sa.String(50), nullable=True),
        sa.Column("contact_website", sa.String(255), nullable=True),
        sa.Column("view_count", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column(
            "created_by",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('simple', "
                "coalesce(title, '') || ' ' || "
                "coalesce(company, '') || ' ' || "
                "coalesce(description, ''))",
                persisted=True,
            ),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.CheckConstraint("salary_min >= 0", name="ck_jobs_salary_min_non_negative"),
        sa.CheckConstraint("salary_max >= 0", name="ck_jobs_salary_max_non_negative"),
        sa.CheckConstraint("view_count >= 0", name="ck_jobs_view_count_non_negative"),
    )
    op.create_index("idx_jobs_active_created", "jobs", ["is_active", "created_at"])
    op.create_index("idx_jobs_category", "jobs", ["category"])
    op.create_index("idx_jobs_created_by", "jobs", ["created_by"])
    op.create_index(
        "idx_jobs_search_vector_gin",
        "jobs",
        ["search_vector"],
        postgresql_using="gin",
    )
    op.create_index(
        "idx_jobs_skills_gin",
        "jobs",
        ["skills"],
        postgresql_using="gin",
    )
    op.create_index(
        "idx_jobs_location_trgm",
        "jobs",
        ["location"],
        postgresql_using="gin",
        postgresql_ops={"location": "gin_trgm_ops"},
    )

    # ── applications ──────────────────────────────────────
    op.create_table(
        "applications",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "job_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("jobs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("resume", sa.String(500), nullable=True),
        sa.Column("cover_letter", sa.Text(), nullable=True),
        sa.Column("phone", sa.String(30), nullable=True),
        sa.Column("telegram", sa.String(50), nullable=True),
        sa.Column(
            "status", APPLICATION_STATUS, nullable=False, server_default="pending"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.UniqueConstraint("user_id", "job_id", name="uq_applications_user_job"),
    )
    op.create_index("idx_applications_job_created", "applications", ["job_id", "created_at"])
    op.create_index("idx_applications_user_created", "applications", ["user_id", "created_at"])

    # ── messages ──────────────────────────────────────────
    op.create_table(
        "messages",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "sender_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "receiver_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "job_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("jobs.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("content", sa.String(2000), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.CheckConstraint("sender_id <> receiver_id", name="ck_messages_no_self_message"),
        sa.CheckConstraint(
            "length(trim(content)) > 0", name="ck_messages_content_non_empty"
        ),
    )
    op.execute(
        "CREATE INDEX idx_messages_pair_created ON messages "
        "(LEAST(sender_id, receiver_id), GREATEST(sender_id, receiver_id), created_at DESC);"
    )
    op.execute(
        "CREATE INDEX idx_messages_receiver_unread ON messages (receiver_id) "
        "WHERE is_read = false;"
    )

    # ── saved_jobs ────────────────────────────────────────
    op.create_table(
        "saved_jobs",
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column(
            "job_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("jobs.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column(
            "saved_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )

    # ── refresh_tokens ────────────────────────────────────
    op.create_table(
        "refresh_tokens",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("token_hash", sa.String(255), nullable=False, unique=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "replaced_by_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("refresh_tokens.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("user_agent", sa.String(255), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.execute(
        "CREATE INDEX idx_refresh_tokens_active_user ON refresh_tokens (user_id) "
        "WHERE revoked_at IS NULL;"
    )


def downgrade() -> None:
    bind = op.get_bind()

    op.drop_table("refresh_tokens")
    op.drop_table("saved_jobs")
    op.drop_table("messages")
    op.drop_table("applications")
    op.drop_table("jobs")
    op.drop_table("users")

    APPLICATION_STATUS.drop(bind, checkfirst=True)
    JOB_TYPE.drop(bind, checkfirst=True)
    EXPERIENCE_LEVEL.drop(bind, checkfirst=True)
    JOB_CATEGORY.drop(bind, checkfirst=True)
    LANG_CODE.drop(bind, checkfirst=True)
    USER_ROLE.drop(bind, checkfirst=True)
