"""Job ORM model — replaces Mongoose `jobs` collection.

Embedded `salary{min,max,currency}` and `contact{phone,telegram,website}`
objects are flattened to columns. `requirements[]` and `skills[]` become
Postgres TEXT arrays. A `tsv` generated column powers full-text search
(replacing the Mongo `$text` index).
"""

from __future__ import annotations

from typing import TYPE_CHECKING
from uuid import UUID

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Computed,
    Enum,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    text,
)
from sqlalchemy.dialects.postgresql import ARRAY, TSVECTOR
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin, UUIDPrimaryKeyMixin
from app.models.enums import ExperienceLevel, JobCategory, JobType

if TYPE_CHECKING:
    from app.models.application import Application
    from app.models.user import User


class Job(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = "jobs"

    title: Mapped[str] = mapped_column(String(200), nullable=False)
    company: Mapped[str] = mapped_column(String(150), nullable=False)
    location: Mapped[str] = mapped_column(String(150), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)

    # ── Salary (flattened) ────────────────────────────────
    salary_min: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    salary_max: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    salary_currency: Mapped[str] = mapped_column(String(3), nullable=False, server_default="USD")

    # ── Lists ─────────────────────────────────────────────
    requirements: Mapped[list[str]] = mapped_column(
        ARRAY(String), nullable=False, server_default=text("'{}'::text[]")
    )
    skills: Mapped[list[str]] = mapped_column(
        ARRAY(String), nullable=False, server_default=text("'{}'::text[]")
    )

    # ── Enums ─────────────────────────────────────────────
    category: Mapped[JobCategory] = mapped_column(
        Enum(JobCategory, name="job_category", values_callable=lambda e: [m.value for m in e]),
        nullable=False,
    )
    experience: Mapped[ExperienceLevel] = mapped_column(
        Enum(
            ExperienceLevel,
            name="experience_level",
            values_callable=lambda e: [m.value for m in e],
        ),
        nullable=False,
        server_default=ExperienceLevel.JUNIOR.value,
    )
    job_type: Mapped[JobType] = mapped_column(
        Enum(JobType, name="job_type", values_callable=lambda e: [m.value for m in e]),
        nullable=False,
        server_default=JobType.FULL_TIME.value,
    )

    # ── Contact (flattened) ───────────────────────────────
    contact_phone: Mapped[str | None] = mapped_column(String(30), nullable=True)
    contact_telegram: Mapped[str | None] = mapped_column(String(50), nullable=True)
    contact_website: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # ── Counters / flags ──────────────────────────────────
    view_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("true"))

    # ── FK ────────────────────────────────────────────────
    created_by: Mapped[UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )

    # ── Full-text search column (generated by Postgres) ───
    search_vector: Mapped[str] = mapped_column(
        TSVECTOR,
        Computed(
            "to_tsvector('simple', "
            "coalesce(title, '') || ' ' || "
            "coalesce(company, '') || ' ' || "
            "coalesce(description, ''))",
            persisted=True,
        ),
    )

    # ── Relationships ─────────────────────────────────────
    creator: Mapped["User"] = relationship(back_populates="jobs")
    applications: Mapped[list["Application"]] = relationship(
        back_populates="job",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )

    __table_args__ = (
        CheckConstraint("salary_min >= 0", name="ck_jobs_salary_min_non_negative"),
        CheckConstraint("salary_max >= 0", name="ck_jobs_salary_max_non_negative"),
        CheckConstraint("view_count >= 0", name="ck_jobs_view_count_non_negative"),
        Index("idx_jobs_active_created", "is_active", "created_at"),
        Index("idx_jobs_category", "category"),
        Index("idx_jobs_created_by", "created_by"),
    )

    def __repr__(self) -> str:
        return f"<Job {self.title} @ {self.company}>"
